[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CCC-Biclustering"
authors = [{name = "Sergio", email = "sergio@sergiomcosta.com"}]
dynamic = ["version", "description"]
